=== LinuxSuRen/phoenix/example/autotest.web.framework/src/main/resources/autotest.web.framework.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://surenpi.com"
	xmlns:suren="http://surenpi.com"
	elementFormDefault="qualified">
	<xs:element name="autotest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="engine" type="suren:engineType" />
				<xs:element name="pages">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="page" type="suren:pageType" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dataSources">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dataSource" type="suren:dataSourceType" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="engineType">
		<xs:attribute name="driver" type="suren:engineTypeDriverEnum" default="chrome" />
		<xs:attribute name="timeout" type="xs:positiveInteger" />
		<xs:attribute name="fullScreen" type="xs:string" />
		<xs:attribute name="width" type="xs:positiveInteger" />
		<xs:attribute name="height" type="xs:positiveInteger" />
	</xs:complexType>
	
	<xs:simpleType name="engineTypeDriverEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="chrome" />
			<xs:enumeration value="firefox" />
			<xs:enumeration value="ie" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="pageType">
		<xs:sequence>
			<xs:element name="field" type="suren:pageFieldType" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="url" type="xs:string" />
		<xs:attribute name="dataSource" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="pageFieldType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="byId" type="xs:string" />
		<xs:attribute name="byCss" type="xs:string" />
		<xs:attribute name="byName" type="xs:string" />
		<xs:attribute name="byXpath" type="xs:string" />
		<xs:attribute name="byLinkText" type="xs:string" />
		<xs:attribute name="byPartialLinkText" type="xs:string" />
		<xs:attribute name="byTagName" type="xs:string" />
		<xs:attribute name="data" type="xs:string" />
		<xs:attribute name="type" type="suren:fieldTypeEnum" default="input" />
		<xs:attribute name="action" type="xs:string" />
	</xs:complexType>
	
	<xs:simpleType name="fieldTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="input" />
			<xs:enumeration value="button" />
			<xs:enumeration value="select" />
			<xs:enumeration value="file_upload" />
			<xs:enumeration value="check_box_group" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="dataSourceType">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="resource" type="xs:string" />
	</xs:complexType>
</xs:schema>

=== LinuxSuRen/phoenix/example/autotest.web.framework/src/test/resources/git.oschina.xml
<?xml version="1.0" encoding="UTF-8"?>
<suren:autotest xmlns:suren="http://surenpi.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://surenpi.com http://surenpi.com/schema/autotest/autotest.web.framework.xsd ">
	<suren:engine driver="chrome" />
	<suren:pages pagePackage="autotest.demo.oschina.page">
		<suren:page class="GitHomePage" url="https://git.oschina.net/">
			<suren:field name="loginBut" type="button" strategy="zone">
				<suren:locators>
					<suren:locator name="byId" value="git-nav-user-bar"/>
					<suren:locator name="byPartialLinkText" value="登录"/>
				</suren:locators>
			</suren:field>
		</suren:page>
		
		<suren:page class="GitLoginPage" dataSource="login_data">
			<suren:field name="userName" type="input" byId="user_login" />
			<suren:field name="password" type="input" byId="user_password" />
		</suren:page>
		
		<suren:page class="GitUserHomePage" dataSource="user_home_data">
			<suren:field name="search" type="input" byId="search_top-search-input"></suren:field>
		</suren:page>
	</suren:pages>
	
	<suren:dataSources>
		<suren:dataSource name="login_data" type="xml_data_source" resource="login_data.xml"/>
		<suren:dataSource name="user_home_data" type="xml_data_source" resource="user_home_data.xml"/>
	</suren:dataSources>
</suren:autotest>
